# Generated by Django 6.0.6 on 2026-06-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("back_end", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlossaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("symptoms", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Entrada de Glossário",
                "verbose_name_plural": "Entradas de Glossário",
                "ordering": ["title"],
            },
        ),
    ]
